parameters:
    my_mailer.transport:  sendmail

services:
    my_mailer:
        class:        Acme\StoreBundle\Mailer
        arguments:    ["%my_mailer.transport%"]
#    acme_store.example:
#        class: Acme\StoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
