fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        acme_elastica:
            client: default
            types:
                product:
                    mappings:
                        id:
                            type: string
                        name :
                            type : string
                        price :
                            type : float
                        description :
                            type : string
                    persistence:
                        driver: mongodb
                        model: Acme\ProductBundle\Document\Product
                        finder: ~
                        provider: ~
                        listener: ~
        search:
            types:
                product:
                    serializer:
                        groups: [acme_elastica, Default]
    serializer: ~