NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

acme_category:
    type: rest
    prefix: /mongodb
    resource: "@AcmeCategoryBundle/Resources/config/routing.yml"

acme_product:
    type: rest
    prefix: /
    resource: "@AcmeProductBundle/Resources/config/routing.yml"
