acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /mongo

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

product:
    resource: Acme\StoreBundle\Controller\ProductController
    type: rest

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

acme_category:
    type: rest
    prefix: /mongo
    resource: "@AcmeCategoryBundle/Resources/config/routing.yml"

acme_product:
    type: rest
    prefix: /mysql
    resource: "@AcmeProductBundle/Resources/config/routing.yml"
