acme_product_document_Category:
    type: rest
    prefix: /mongo
    resource: "Acme\\ProductBundle\\Controller\\ProductDocumentController"
    name_prefix:  mongodb_ # naming collision

acme_product_entity_Category:
    type: rest
    prefix: /mysql
    resource: "Acme\\ProductBundle\\Controller\\ProductEntityController"
    name_prefix:  mysql_ # naming collision
